__author__ = 'kamran'


class form_locators:
    click_sign_button = '.quantumWizDialogPaperdialogBottomButtons div:nth-child(2) span'
    email_locator = 'input[autocomplete="username"]'
    password_locator = 'input[autocomplete="current-password"]'
    validators_selector = 'div[role="alert"]'
    # title = 'Automation Assessment'
    cnic = "[aria-label|=CNIC]"
    email = "[aria-label|=Email]"
    name = "[aria-label|=Name]"
    phone = '[aria-label="Phone Number"]'
    next_button = "[jsname|=OCpkoe]"
    pageTitle = '.freebirdMaterialHeaderbannerPagebreakText'
    Mcqs = 'div[data-other-hidden="MfYA1e"] div[role="heading"]'
    mcq_1_selector = '.freebirdFormviewerViewItemsItemItem label div[aria-label="{}"]'
    chack_box_qutz = 'div[data-other-hidden="MfYA1e"] div[role="heading"]'
    chack_box_ans = 'div[data-value="{}"] label div.quantumWizTogglePapercheckboxEl'
    capitals_mcqs = 'div.freebirdFormviewerViewItemsItemItemTitle.freebirdCustomFont[role="heading"]'
    cap_pun_selector = 'div[data-item-id="543587841"] div[aria-describedby="i.desc.543587841 i.err.543587841"]'
    cap_pak_selector = 'div[data-item-id="434999194"] div[aria-describedby="i.desc.434999194 i.err.434999194"]'
    capitals_ans = 'div.exportSelectPopup .quantumWizMenuPaperselectOption[data-value="{}"]'
    upload_files_text = '[aria-label="Add file"] content'
    add_files = '.picker.modal-dialog.picker-dialog:nth-last-child(2) .picker-frame'
    my_drive = 'div[id=":6"]'
    upload_pdf = 'div[data-target="doc"]:nth-child(1)'
    select_file = 'div[role="button"][id="picker:ap:2"]'
    scale = 'div.freebirdFormviewerViewItemsItemItemTitle.freebirdCustomFont[role="heading"]'
    scale_assisment = 'div.freebirdMaterialScalecontentContainer label'
    choice_grides = 'div.freebirdFormviewerViewItemsItemItemTitle.freebirdCustomFont[role="heading"]'
    get_gride_text = 'content[role="presentation"] div.freebirdFormviewerViewItemsGridCell.freebirdFormviewerViewItemsGridRowHeader'
    #'#'content[role="presentation"]>div'
    set_gride_text = 'div[aria-label="{}"] label'
    chack_box_gride_selc = 'div.freebirdFormviewerViewItemsGridRowGroup.freebirdFormviewerViewItemsGridCheckboxGroup.freebirdFormviewerViewItemsGridUngraded>div'
    reading_selector = '[aria-label="Reading, response for {}"]'
    listing_selector = '[aria-label="Listening, response for {}"]'
    writing_selector = '[aria-label="Writing, response for {}"]'
    date_drop = 'div[aria-label="Enter Current date"] input[autocomplete="off"]'
    input_date = 'input[type="date"]'
    Hours = 'input[aria-label="Hour"]'
    Minut = 'input[aria-label="Minute"]'
    form_submit = 'div.freebirdFormviewerViewNavigationButtons div:nth-child(2)'
    view_confirmation_response = "div.freebirdFormviewerViewResponsePageTitle.freebirdCustomFont"
    view_page_source_button = 'a[aria-label="View score"]'

    use_fire_bug = 'div.freebirdFormviewerViewFormCard.exportFormCard:nth-child(2) div:nth-child(3) div.freebirdFormviewerViewItemsItemItemTitle.exportItemTitle.freebirdCustomFont'
    ans_inspect_element = 'div.freebirdFormviewerViewFormCard.exportFormCard:nth-child(2) content div[data-value="Inspecting Elements"]'
    selec_name_not_type_locator = 'div.freebirdFormviewerViewFormCard.exportFormCard:nth-child(2) div:nth-child(4) div.freebirdFormviewerViewItemsItemItemTitle.exportItemTitle.freebirdCustomFont'
    ans_password = 'div.freebirdFormviewerViewFormCard.exportFormCard:nth-child(2) content div[data-value="Password"]'
    two_num_that_not_prime = 'div.freebirdFormviewerViewFormCard.exportFormCard:nth-child(3) div:nth-child(3) div[role="listitem"] [aria-level="2"]'
    list_two_num_taht_not_prim = 'div[data-item-id="639199141"] div.freebirdFormviewerViewItemsItemGradingGradingBox span[dir="auto"]'
    select_correct_ans = 'div.freebirdFormviewerViewFormCard.exportFormCard:nth-child(3) div:nth-child(4) div[role="listitem"] [aria-level="2"]'
    list_select_correct_ans = 'div[data-item-id="1944594563"] div.freebirdFormviewerViewItemsItemGradingGradingBox span[dir="auto"]'
    capital_of_pakistan = 'div.freebirdFormviewerViewFormCard.exportFormCard:nth-child(4) div:nth-child(3) div.freebirdFormviewerViewItemsItemItemTitle.exportItemTitle.freebirdCustomFont'
    islamabad = 'div.freebirdFormviewerViewFormCard.exportFormCard:nth-child(4) div[role="list"] div:nth-child(3) div.freebirdFormviewerViewItemsItemGradingGradingBox div.freebirdFormviewerViewItemsSelectLabel'
    # islamabad = 'div.freebirdFormviewerViewItemsSelectChoice.freebirdFormviewerViewItemsSelectSelected.freebirdFormviewerViewItemsSelectCorrect:nth-child(1)'
    capital_of_punjab = 'div.freebirdFormviewerViewFormCard.exportFormCard:nth-child(4) div:nth-child(4) div.freebirdFormviewerViewItemsItemItemTitle.exportItemTitle.freebirdCustomFont'
    lahore = 'div.freebirdFormviewerViewFormCard.exportFormCard:nth-child(4) div[role="list"] div:nth-child(4) div.freebirdFormviewerViewItemsItemGradingGradingBox div.freebirdFormviewerViewItemsSelectLabel'
    # lahore = 'div.freebirdFormviewerViewNumberedItemContainer:nth-child(3) div.freebirdFormviewerViewItemsSelectChoice.freebirdFormviewerViewItemsSelectSelected.freebirdFormviewerViewItemsSelectCorrect'

